#!/bin/bash

echo -e "$(date +'%Y/%m/%d %H:%M:%S')\t" "$0" "$@"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "${SCRIPT_DIR}/common"

main() {
    clear_chroot_build_failure_lock || return 1
    restore_default_module_package
}

main "$@"
